[project]
name = "nasa-spacepath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=1.1.0",
    "fastapi>=0.118.0",
    "flask>=3.1.2",
    "langchain>=0.3.27",
    "langchain-community>=0.3.21",
    "langchain-openai>=0.3.34",
    "matplotlib>=3.10.6",
    "negspacy>=1.0.4",
    "networkx>=3.5",
    "pandas>=2.3.3",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.11.0",
    "pyvis>=0.3.2",
    "scispacy>=0.6.2",
    "sentence-transformers>=5.1.1",
    "spacy>=3.8.7",
    "tqdm>=4.67.1",
    "uuid>=1.30",
    "yake>=0.6.0",
]
